Description: <short summary of the patch>
 TODO: Put a short summary on the line above and replace this paragraph
 with a longer explanation of this change. Complete the meta-information
 with other relevant fields (see below for details). To make it easier, the
 information below has been extracted from the changelog. Adjust it or drop
 it.
 .
 libyuv (0.0.1280-1) unstable; urgency=low
 .
   * Initial release (Closes: #nnnn)  <nnnn is the bug number of your ITP>
Author: William King <william.king@quentustech.com>

---
The information above should follow the Patch Tagging Guidelines, please
checkout http://dep.debian.net/deps/dep3/ to learn about the format. Here
are templates for supplementary fields that you might want to add:

Origin: <vendor|upstream|other>, <url of original patch>
Bug: <url in upstream bugtracker>
Bug-Debian: https://bugs.debian.org/<bugnumber>
Bug-Ubuntu: https://launchpad.net/bugs/<bugnumber>
Forwarded: <no|not-needed|url proving that it has been forwarded>
Reviewed-By: <name and email of someone who approved the patch>
Last-Update: <YYYY-MM-DD>

--- /dev/null
+++ libyuv-0.0.1280/Makefile
@@ -0,0 +1,68 @@
+# This is a generic makefile for libyuv for gcc.
+# make -f linux.mk CXX=clang++
+
+PREFIX=/usr
+LIBDIR=$(DESTDIR)/$(PREFIX)/lib/
+INCDIR=$(DESTDIR)/$(PREFIX)/include/
+
+CXX?=g++
+CXXFLAGS?=-O2 -fomit-frame-pointer -fpic
+CXXFLAGS+=-Iinclude/
+LDFLAGS      = -shared
+
+LOCAL_OBJ_FILES := \
+    source/compare.o           \
+    source/compare_common.o    \
+    source/compare_posix.o     \
+    source/convert.o           \
+    source/convert_argb.o      \
+    source/convert_from.o      \
+    source/convert_from_argb.o \
+    source/convert_to_argb.o   \
+    source/convert_to_i420.o   \
+    source/cpu_id.o            \
+    source/planar_functions.o  \
+    source/rotate.o            \
+    source/rotate_argb.o       \
+    source/rotate_mips.o       \
+    source/row_any.o           \
+    source/row_common.o        \
+    source/row_mips.o          \
+    source/row_posix.o         \
+    source/scale.o             \
+    source/scale_argb.o        \
+    source/scale_common.o      \
+    source/scale_mips.o        \
+    source/scale_posix.o       \
+    source/video_common.o
+
+.cc.o:
+	$(CXX) -c $(CXXFLAGS) $*.cc -o $*.o
+
+all: libyuv.a libyuv.so convert
+
+libyuv.a: $(LOCAL_OBJ_FILES)
+	$(AR) $(ARFLAGS) $@ $(LOCAL_OBJ_FILES)
+
+libyuv.so: $(LOCAL_OBJ_FILES)
+	$(CXX) $(CXXFLAGS) $(LOCAL_OBJ_FILES) -o $@ $(LDFLAGS)
+
+# A test utility that uses libyuv conversion.
+convert: util/convert.cc libyuv.a
+	$(CXX) $(CXXFLAGS) -Iutil/ -o $@ util/convert.cc libyuv.a
+
+clean:
+	/bin/rm -f source/*.o *.ii *.s libyuv.a convert
+
+install: libyuv.a libyuv.so
+	install -d -m 755 $(LIBDIR)
+	install -d -m 755 $(INCDIR)
+	install -d -m 755 $(INCDIR)/libyuv
+	install -d -m 755 $(LIBDIR)/pkgconfig
+	install -m 644 libyuv.a $(LIBDIR)
+	install -m 644 libyuv.so $(LIBDIR)
+	install -m 644 libyuv.pc $(LIBDIR)/pkgconfig
+	install -m 644 include/libyuv.h $(INCDIR)
+	install -m 644 include/libyuv/* $(INCDIR)/libyuv
+
+
--- /dev/null
+++ libyuv-0.0.1280/libyuv.pc
@@ -0,0 +1,10 @@
+prefix=/usr
+exec_prefix=${prefix}
+libdir=/usr/lib
+includedir=${prefix}/include
+
+Name: libyuv
+Description: libyuv
+Version: 0.0.1280
+Cflags: -I${includedir}
+Libs: -L${libdir} -lyuv
